package com.siat.stcloud.pojos;
// Generated 15-jun-2014 1:34:04 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Archivo generated by hbm2java
 */
public class Archivo  implements java.io.Serializable {


     private Integer idArchivo;
     private Carpeta carpeta;
     private String nombre;
     private Date fechaCreacion;
     private String ruta;

    public Archivo() {
    }

	
    public Archivo(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Archivo(Carpeta carpeta, String nombre, Date fechaCreacion, String ruta) {
       this.carpeta = carpeta;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.ruta = ruta;
    }
   
    public Integer getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(Integer idArchivo) {
        this.idArchivo = idArchivo;
    }
    public Carpeta getCarpeta() {
        return this.carpeta;
    }
    
    public void setCarpeta(Carpeta carpeta) {
        this.carpeta = carpeta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }




}


