package com.siat.stcloud.pojos;
// Generated 15-jun-2014 1:34:04 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Carpeta generated by hbm2java
 */
public class Carpeta  implements java.io.Serializable {


     private Integer idCarpeta;
     private Grupo grupo;
     private Usuario usuario;
     private String cptNombre;
     private Date cptFechaCreacion;
     private String cptRuta;
     private Set archivos = new HashSet(0);

    public Carpeta() {
    }

	
    public Carpeta(Date cptFechaCreacion) {
        this.cptFechaCreacion = cptFechaCreacion;
    }
    public Carpeta(Grupo grupo, Usuario usuario, String cptNombre, Date cptFechaCreacion, String cptRuta, Set archivos) {
       this.grupo = grupo;
       this.usuario = usuario;
       this.cptNombre = cptNombre;
       this.cptFechaCreacion = cptFechaCreacion;
       this.cptRuta = cptRuta;
       this.archivos = archivos;
    }
   
    public Integer getIdCarpeta() {
        return this.idCarpeta;
    }
    
    public void setIdCarpeta(Integer idCarpeta) {
        this.idCarpeta = idCarpeta;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCptNombre() {
        return this.cptNombre;
    }
    
    public void setCptNombre(String cptNombre) {
        this.cptNombre = cptNombre;
    }
    public Date getCptFechaCreacion() {
        return this.cptFechaCreacion;
    }
    
    public void setCptFechaCreacion(Date cptFechaCreacion) {
        this.cptFechaCreacion = cptFechaCreacion;
    }
    public String getCptRuta() {
        return this.cptRuta;
    }
    
    public void setCptRuta(String cptRuta) {
        this.cptRuta = cptRuta;
    }
    public Set getArchivos() {
        return this.archivos;
    }
    
    public void setArchivos(Set archivos) {
        this.archivos = archivos;
    }




}


