package com.siat.stcloud.pojos;
// Generated 15-jun-2014 1:34:04 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private Integer idUsuario;
    private String usrNombre;
    private String usrGenero;
    private Date usrFechaNacimiento;
    private String usrEmail;
    private String usrUsuario;
    private String usrContrasenia;
    private String usrPrivilegios;
    private Set carpetas = new HashSet(0);
    private Set usuarioGrupos = new HashSet(0);
    private Set grupos = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String usrNombre, String usrGenero, Date usrFechaNacimiento, String usrEmail, String usrUsuario, String usrContrasenia, String usrPrivilegios, Set carpetas, Set usuarioGrupos, Set grupos) {
        this.usrNombre = usrNombre;
        this.usrGenero = usrGenero;
        this.usrFechaNacimiento = usrFechaNacimiento;
        this.usrEmail = usrEmail;
        this.usrUsuario = usrUsuario;
        this.usrContrasenia = usrContrasenia;
        this.usrPrivilegios = usrPrivilegios;
        this.carpetas = carpetas;
        this.usuarioGrupos = usuarioGrupos;
        this.grupos = grupos;
    }

    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getUsrNombre() {
        return this.usrNombre;
    }

    public void setUsrNombre(String usrNombre) {
        this.usrNombre = usrNombre;
    }

    public String getUsrGenero() {
        return this.usrGenero;
    }

    public void setUsrGenero(String usrGenero) {
        this.usrGenero = usrGenero;
    }

    public Date getUsrFechaNacimiento() {
        return this.usrFechaNacimiento;
    }

    public void setUsrFechaNacimiento(Date usrFechaNacimiento) {
        this.usrFechaNacimiento = usrFechaNacimiento;
    }

    public String getUsrEmail() {
        return this.usrEmail;
    }

    public void setUsrEmail(String usrEmail) {
        this.usrEmail = usrEmail;
    }

    public String getUsrUsuario() {
        return this.usrUsuario;
    }

    public void setUsrUsuario(String usrUsuario) {
        this.usrUsuario = usrUsuario;
    }

    public String getUsrContrasenia() {
        return this.usrContrasenia;
    }

    public void setUsrContrasenia(String usrContrasenia) {
        this.usrContrasenia = usrContrasenia;
    }

    public String getUsrPrivilegios() {
        return this.usrPrivilegios;
    }

    public void setUsrPrivilegios(String usrPrivilegios) {
        this.usrPrivilegios = usrPrivilegios;
    }

    public Set getCarpetas() {
        return this.carpetas;
    }

    public void setCarpetas(Set carpetas) {
        this.carpetas = carpetas;
    }

    public Set getUsuarioGrupos() {
        return this.usuarioGrupos;
    }

    public void setUsuarioGrupos(Set usuarioGrupos) {
        this.usuarioGrupos = usuarioGrupos;
    }

    public Set getGrupos() {
        return this.grupos;
    }

    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }
}
